version: '3.3'

services:
  postgresql:
    image: postgresql:12
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      postgresql_ROOT_PASSWORD: 'password'
    volumes:
      - postgresql:/var/lib/postgresql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']
volumes:
  postgresql:
  redis:
